from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from compiler import compile_and_run  # noqa: E402


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="MiniLang compiler runner")
    src_group = parser.add_mutually_exclusive_group(required=True)
    src_group.add_argument("--file", type=str, help="Path to .lang source file")
    src_group.add_argument("--source", type=str, help="MiniLang source code as a string")
    parser.add_argument("--no-run", action="store_true", help="Compile only (do not execute)")
    parser.add_argument("--print-bytecode", action="store_true", help="Print generated bytecode")
    args = parser.parse_args(argv)

    if args.file:
        path = Path(args.file)
        source = path.read_text(encoding="utf-8-sig")
    else:
        source = args.source

    result = compile_and_run(source=source, run=not args.no_run)

    if args.print_bytecode:
        import json

        print(json.dumps(result.bytecode, indent=2))

    if not result.ok:
        print("ERROR:", result.error_text)
        return 1

    if not args.no_run:
        print(result.output_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

